# Generated by Django 5.1.1 on 2025-12-29 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profile_picture',
            field=models.ImageField(blank=True, default='https://i.pravatar.cc/200', upload_to='profile_pics/'),
        ),
    ]
