# Generated by Django 5.1.1 on 2025-12-30 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0002_employee_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('overdue', 'Overdue')], default='pending', max_length=10),
        ),
    ]
