# Generated by Django 6.0 on 2025-12-31 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0003_employee_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_picture',
            field=models.ImageField(blank=True, default='https://i.pravatar.cc/200', null=True, upload_to='profile_pics/'),
        ),
    ]
